### ISSUE TITLE
Approvazione Project plan

### ISSUE THREAD

**Issue by drevrena** [fassolari1/MyWallet#2]

**Comment by garganti** [comment]
Sì va bene il project plan. Alcune cose non mi sembrano tanto SCRUM il fatto che tutti fanno tutto - però immagino che sia perchè siete tutti alla pari. Il budget poi forse potevato farlo in termini di tempo e non si soldi ma ok. poi importante **mettete il codice in una sotto directory della root non mischiate il tutto** ad esempio sotto codice mettere il progetto eclipse e sotto doc i documenti vari
